// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Matias-Barrios/wire-test/config"
	"github.com/Matias-Barrios/wire-test/handlers"
)

// Injectors from wire.go:

func InitializeApp() (App, error) {
	configConfig := config.LoadConfig()
	iHealthHandler := handlers.NewHealthHandler()
	router := handlers.NewRouter(iHealthHandler)
	app, err := NewApp(configConfig, router)
	if err != nil {
		return App{}, err
	}
	return app, nil
}
